spring:
  application:
    name: t1
  datasource:
    url: "jdbc:postgresql://localhost:5430/t1"
    username: t1_user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: none
  liquibase:
    enabled: true
logging:
  level:
    com.t1.aop: DEBUG
    root: info
server:
  port: 8080
