--changeset merkodanov:1
CREATE TABLE time_limit_exceed_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    signature      VARCHAR(1000),
    execution_time BIGINT                                  NOT NULL,
    CONSTRAINT pk_timelimitexceedlog PRIMARY KEY (id)
);