--changelog merkodanov:1
CREATE TABLE data_source_error_log
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stack_trace         TEXT,
    message             VARCHAR(255),
    signature_of_method VARCHAR(255),
    CONSTRAINT pk_datasourceerrorlog PRIMARY KEY (id)
);