--changeset merkodanov:1
CREATE TABLE client
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    first_name  VARCHAR(255),
    middle_name VARCHAR(255),
    last_name   VARCHAR(255)
);
--changeset merkodanov:2
CREATE TABLE account
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    balance   DECIMAL               NULL,
    type      VARCHAR(50)              NULL,
    client_id BIGINT                NOT NULL
);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);
--changeset merkodanov:3
CREATE TABLE transaction
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    total_amount DECIMAL,
    time         TIMESTAMP WITHOUT TIME ZONE,
    account_id   BIGINT                                  NOT NULL
);

ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);